export const menuData = [
  { id: 1, name: "Margherita Pizza", desc: "Classic cheese & tomato", price: "₹299" },
  { id: 2, name: "Farmhouse Pizza", desc: "Loaded with veggies", price: "₹399" },
  { id: 3, name: "Pepperoni Pizza", desc: "Spicy pepperoni & cheese", price: "₹449" },
  { id: 4, name: "Veggie Delight Pizza", desc: "Bell peppers, olives, onions", price: "₹399" },
  { id: 5, name: "Cheese Burst Pizza", desc: "Extra cheesy goodness", price: "₹499" },
  { id: 6, name: "Paneer Tikka Pizza", desc: "Paneer & spices", price: "₹449" },
  { id: 7, name: "Mexican Green Wave", desc: "Jalapenos & bell peppers", price: "₹449" },
  { id: 8, name: "Chicken Golden Delight", desc: "Chicken & creamy sauce", price: "₹499" },
  { id: 9, name: "Veg Extravaganza", desc: "Loaded with all veggies", price: "₹499" },
  { id: 10, name: "Cheese n Corn Pizza", desc: "Sweet corn & cheese", price: "₹399" },
  { id: 11, name: "Garlic Bread", desc: "Toasted perfection with herbs", price: "₹149" },
  { id: 12, name: "Cheesy Garlic Bread", desc: "Extra cheesy garlic bread", price: "₹199" },
  { id: 13, name: "Pasta Alfredo", desc: "Creamy white sauce pasta", price: "₹349" },
  { id: 14, name: "Pasta Arrabiata", desc: "Spicy tomato pasta", price: "₹329" },
  { id: 15, name: "Veg Lasagna", desc: "Layered veggies & cheese", price: "₹399" },
  { id: 16, name: "Chicken Lasagna", desc: "Layers of chicken & cheese", price: "₹449" },
  { id: 17, name: "Veg Burger", desc: "Grilled veggie patty & cheese", price: "₹199" },
  { id: 18, name: "Cheese Burger", desc: "Classic beef & cheese", price: "₹249" },
  { id: 19, name: "Veg Sandwich", desc: "Fresh veggies & cheese", price: "₹149" },
  { id: 20, name: "Grilled Chicken Sandwich", desc: "Juicy grilled chicken", price: "₹199" },
  { id: 21, name: "Paneer Wrap", desc: "Spicy paneer in a wrap", price: "₹179" },
  { id: 22, name: "Chicken Wrap", desc: "Grilled chicken wrap", price: "₹199" },
  { id: 23, name: "French Fries", desc: "Crispy golden fries", price: "₹99" },
  { id: 24, name: "Cheese Fries", desc: "Fries with melted cheese", price: "₹149" },
  { id: 25, name: "Onion Rings", desc: "Crispy onion rings", price: "₹129" },
  { id: 26, name: "Cold Coffee", desc: "Chilled & creamy delight", price: "₹129" },
  { id: 27, name: "Iced Latte", desc: "Refreshing coffee drink", price: "₹149" },
  { id: 28, name: "Cappuccino", desc: "Classic frothy coffee", price: "₹129" },
  { id: 29, name: "Espresso", desc: "Strong & bold", price: "₹99" },
  { id: 30, name: "Mocha", desc: "Chocolate flavored coffee", price: "₹149" },
  { id: 31, name: "Green Tea", desc: "Healthy green tea", price: "₹79" },
  { id: 32, name: "Lemon Tea", desc: "Refreshing lemon tea", price: "₹79" },
  { id: 33, name: "Herbal Tea", desc: "Relaxing herbal blend", price: "₹99" },
  { id: 34, name: "Masala Chai", desc: "Indian spiced tea", price: "₹79" },
  { id: 35, name: "Veg Pizza Slice", desc: "Quick snack slice", price: "₹99" },
  { id: 36, name: "Chicken Pizza Slice", desc: "Spicy chicken slice", price: "₹129" },
  { id: 37, name: "Cheese Pizza Slice", desc: "Slice with extra cheese", price: "₹119" },
  { id: 38, name: "Veg Salad", desc: "Fresh garden veggies", price: "₹149" },
  { id: 39, name: "Chicken Caesar Salad", desc: "Classic Caesar with chicken", price: "₹199" },
  { id: 40, name: "Greek Salad", desc: "Olives, feta & veggies", price: "₹179" },
  { id: 41, name: "Paneer Salad", desc: "Grilled paneer & veggies", price: "₹159" },
  { id: 42, name: "Chocolate Brownie", desc: "Fudgy chocolate delight", price: "₹129" },
  { id: 43, name: "Vanilla Ice Cream", desc: "Classic vanilla scoop", price: "₹99" },
  { id: 44, name: "Chocolate Ice Cream", desc: "Rich chocolate flavor", price: "₹129" },
  { id: 45, name: "Strawberry Ice Cream", desc: "Fresh strawberry taste", price: "₹129" },
  { id: 46, name: "Fruit Salad", desc: "Mix of fresh fruits", price: "₹149" },
  { id: 47, name: "Cold Drink (Coke/Sprite)", desc: "Chilled soda", price: "₹79" },
  { id: 48, name: "Lassi", desc: "Sweet or salty yogurt drink", price: "₹99" },
  { id: 49, name: "Mango Shake", desc: "Fresh mango blend", price: "₹149" },
  { id: 50, name: "Banana Shake", desc: "Creamy banana flavor", price: "₹129" },
  { id: 51, name: "Strawberry Shake", desc: "Sweet strawberry shake", price: "₹149" },
];
